services:
  postgres:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_USER: ft-user
      POSTGRES_PASSWORD: ft-password
      POSTGRES_DB: feature_tracker
    ports:
      - "5432"
    profiles:
      - dev
  mongodb:
    image: mongodb/mongodb-community-server:6.0.18-ubi9
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017"
    profiles:
        - dev
